### ISSUE TITLE
Turn README into wiki

### ISSUE THREAD

**Issue by Honestpuck** [univ-of-utah-marriott-library-apple/python-jamf#12]
Not really an issue. Just a point I wanted to raise for discussion. The README is now getting to a length and if I add documentation for my work it will get longer.

So how do you feel about me taking the existing README and my documentation and turning it onto a shorter README and a wiki? I was thinking of just a top page and only one layer of sub pages corresponding with the current headlines.

I also have no idea if I can PR the wiki but I'm guessing I can.

**Comment by Tophernad** [comment]
Hey Tony,
I think that is a great idea. Having a more detailed wiki is nice for bigger projects.  I’m not sure how to merge a wiki but we can figure it out. 
Topher

**Comment by Honestpuck** [comment]
OK. I'll do it over the next few days while working on `test_records.py`.

**Comment by Honestpuck** [comment]
[python-jamf.wiki.zip](https://github.com/univ-of-utah-marriott-library-apple/python-jamf/files/5752999/python-jamf.wiki.zip)

You can't do a PR for the wiki so here is a first crack at it. Clone down the blank wiki, drop these in there and push back to GitHub.

**Comment by Tophernad** [comment]
The wiki has been updated with the info that you provided. The README needs to be updated to reflect that there is a Wiki now.
