### ISSUE TITLE
Add Support for Detecting Jamf Pro Version & Bearer Token Authentication

### ISSUE THREAD

**Issue by uurazzle** [univ-of-utah-marriott-library-apple/python-jamf#67]
Hi:

Jamf will deprecate support for Basic Authentication in Jamf Pro v10.35.0 or later. `python-jamf` will need to add support for Bearer Token authentication by implementing a [version check](https://developer.jamf.com/jamf-pro/reference-link/jamf-pro-version-1) of Jamf Pro, your application can determine whether Bearer Token authentication is supported (v10.35.0 or later) or if use of Basic authentication is required (v10.34.0 and earlier).

The jamf-pro-version endpoint within the Jamf Pro API returns the version of the Jamf Pro Server, to help your application determine authentication compatibility with a given Jamf Pro Server. Jamf recommends including a preference to allow users to select the authentication schema based on their environment configuration or dynamically determining which authentication mechanism to use based on the Jamf Pro Server version.

In addition to the recommendations provided above, Jamf has updated the [Classic API Postman Collection](https://github.com/jamf/Classic-API-Postman-Collection) to now default to the use of Bearer Token authentication. Older versions of the collection will continue to be available for interaction with environments not yet upgraded to 10.35.0 or later, however the new collection will default to using Bearer Token authentication.

Additional details regarding the changes, including best practices are detailed on the [Jamf Developer Portal](https://developer.jamf.com/jamf-pro/docs/classic-api-authentication-changes).

**Comment by magnusviri** [comment]
Fixed in [65bec39](https://github.com/univ-of-utah-marriott-library-apple/python-jamf/commit/65bec39b7eb40698c09f9fd1338bcfd3b4fe8854)
