### ISSUE TITLE
Virtual environment documentation

### ISSUE THREAD

**Issue by pythoninthegrass** [univ-of-utah-marriott-library-apple/python-jamf#70]
Unable to [open a PR](https://macadmins.slack.com/archives/C01C8KVV2UD/p1645286233000709) for wiki edits. 

Please see [this fork](https://github.com/pythoninthegrass/python-jamf/wiki/More#virtual-environment) for my modest documentation contribution.

**Comment by pythoninthegrass** [comment]
The [changes look great](https://github.com/univ-of-utah-marriott-library-apple/python-jamf/wiki/More#virtual-environments) @uurazzle ! Since wikis are hostile to PRs, here's the changes to `More.md` I was suggesting in [MacAdmins](https://macadmins.slack.com/archives/C01C8KVV2UD/p1645665265361379):

  #### Install `python-jamf`
Next, to install `python-jamf` in your virtual environment, enter the following command:
```bash
% pip3 install python-jamf

```
To verify its installed properly, enter the following command:

```bash
% pip list
Package            Version
------------------ ----------------
certifi            2021.10.8
chardet            3.0.4
idna               2.10
importlib-metadata 4.11.1
keyring            23.5.0
pip                21.2.4
python-jamf        0.7.3-2-gd517792
requests           2.24.0
setuptools         58.1.0
urllib3            1.25.11
zipp               3.7.0

```


#### Configure Jamf Pro Credentals
Next, to configure you Jamf Pro server credentials, enter the following command:

```bash
% conf-python-jamf

Hostname (don't forget https:// and :8443): https://jamf.example.edu:8443
Username: [MyAPIUser]
Password: [hidden]
2021-11-19 21:11:15,100:     INFO: jamf.config.Config - save(): saving: /Users/[UserAccountName]/Library/Preferences/edu.utah.mlib.jamfutil.plist

```


#### Test the Connection
Next, to test the setup of `python-jamf` and your Jamf Pro server credentals & settings, enter the following command:

```bash
% conf-python-jamf -t
{'accounts': {'groups': None, 'users': {'user': {'id': '1', 'name': 'richard'}}}}

```
For more details on usage, please see [Testing Installation with Python](https://github.com/univ-of-utah-marriott-library-apple/python-jamf/wiki/Installing#testing-installation-with-python)

#### Exit Virtual Environment

(added your missing `pip list`, a blurb about looking at library usage in another castle, and fixed the typo, `Ennvironment`.)

**Comment by uurazzle** [comment]
Hi @pythoninthegrass:

Thanks for the contributions. I added the missing `pip list`, fixed the misspelling for `Ennvironment`, and fixed other grammar and spelling issues in addition.

Let us know if you want to contribute anything else to the project. Maybe, unit tests? Noted, in the [Running Tests](https://github.com/univ-of-utah-marriott-library-apple/python-jamf/wiki/More#running-tests) section?
