### ISSUE TITLE
FileShare.mount uses macOS binaries and thus does not support linux

### ISSUE THREAD

**Issue by yairf-s1** [univ-of-utah-marriott-library-apple/python-jamf#71]
SMB could be supported using pysmb (without subprocess calls)
I'm not sure about AFP though.

We could also use 'mount' for linux machines (but then im unsure about other bsd distros)

**Comment by uurazzle** [comment]
Hi @yairf-s1:

Thanks for the feedback. Is this the `python.py` or `jctl` script? And interest in code contributions?

**Comment by yairf-s1** [comment]
I've already opened a PR, but i'm probably not going to use it, so i won't be able to field test it myself

**Comment by magnusviri** [comment]
Your PR has been merged. I haven't tested it, so I hope it works.
