### ISSUE TITLE
test_config problems with config.PREFERENCES

### ISSUE THREAD

**Issue by Honestpuck** [univ-of-utah-marriott-library-apple/python-jamf#8]

**Comment by Honestpuck** [comment]
There are some problems with test_config and I can't see what should be done as I'm not over that code.

The test code tries to use a variable `config.PREFERENCES` which doesn't exist. I'm not sure how it uses this variable.

**Comment by Tophernad** [comment]
Hey Tony,
When we split the repo, config.py had elements removed from it as it was part of jctl. I have added some of the elements back but it uses a new call. It is something I can look at. 
Topher

**Comment by magnusviri** [comment]
I've finally re-written the config test so this finally is fixed.
